account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "users"
urlpatterns = [
    path('', views.login, name='login'),
    path('logout/', views.logout, name='logout'), # 코드 추가하기
    path('signup', views.signup, name='signup')
]

blog/urls.py
from django.urls import path
from . import views
urlpatterns =[  
    path('',views.blog_views, name='blog_views'),
    path('<str:id>', views.detail, name='detail'),
    path('update/<str:id>', views.update, name='update'),
    path('delete/<str:id>', views.delete, name='delete'),
    path('post/', views.make_post, name='post'),
    path('create_comment/<int:blog_id>', views.create_comment, name='create_comment'),
    path('delete_comment/<int:blog_id>/<int:comment_id>/', views.delete_comment, name='delete_comment')
]

blogproject/urls.py
from django.contrib import admin
from django.urls import path, include
from blog import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')), # blog app에 urls를 새로 만들어준 다음에 include를 사용해서 보기 쉽게 만들어준다.
    path('account/', include('account.urls')),
    path('', views.main, name="main")
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

 

# static과 settings를 임포트해주고, 기존의 urlpatterns에 settings.py에서 정의한 미디어 경로를 추가한다.

# 이렇게 코드를 추가함으로써 이미지는 테이블 속성 값으로 이미지 자체로 저장되어있는 것이 아닌 '/media/이미지이름.png' 처럼 path가 저장된다.

# 맨 아래 코드가 추가 코드임.

account/models.py
from django.db import models


# Create your models here.

blog/models.py
from django.db import models
# Create your models here.
class BLog(models.Model):
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=50)
    pub_date = models.DateField()
    body = models.TextField()
    image = models.ImageField(upload_to="blog/", blank=True, null=True)

    def __str__(self):
        return self.title

class Comment(models.Model):
    content = models.CharField(max_length=200)
    author = models.CharField(max_length=50)
    blog = models.ForeignKey(BLog,on_delete=models.CASCADE)
    create_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

account/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.models import User
from django.contrib import auth
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.forms import ValidationError
from django import forms
from .validator import validate_score

# Create your views here.
def test(request):
    print("정상 영업합니다.")

def signup(request):
    # if request.method == 'POST':
    #     memo = forms.CharField(max_length=80, validators= [validate_score])
    if request.method == 'POST':
        if User.objects.filter(username=request.POST['username']).exists(): #아이디 중복 체크 
           raise ValidationError("아이디가 이미 사용중입니다.")
        if request.POST['password'] == request.POST['confirm']:
            user = User.objects.create_user(username=request.POST['username'], password=request.POST['password'])
            auth.login(request, user)
            print("username")
            return redirect('blog_views')
    return render(request, 'signup.html')

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(request, username=username, password=password)
        
        if user is not None:
            auth.login(request, user)
            print("12345")
            return redirect('blog_views')
        else:
            return render(request, 'login.html', {'error' : 'username or password is incorrect.'})
    else:
        return render(request, 'login.html')


def logout(request):
    auth.logout(request)
    return redirect('blog_views')

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from django.utils import timezone
# Create your views here.
def main(request):
    return render(request, 'index.html')

def blog_views(request):
    blogs = BLog.objects.all()
    # return render(request, 'home.html', {'blogs':blogs})
    return render(request,'home.html', {'blogs':blogs})

def detail(request,id):
    blog = get_object_or_404(BLog, pk=id)
    return render(request, 'detail.html', {'blog' : blog})

def new(request):
    return render(request,'new.html')

def create(request):
    new_blog = BLog()
    new_blog.title = request.POST['title']
    new_blog.author = request.POST['author']
    new_blog.image = request.FILES['image']
    new_blog.body = request.POST['body']
    new_blog.pub_date = timezone.now()
    new_blog.save()
    return redirect('blog_views')


def edit(request,id):
    blog = BLog.objects.get(id = id)
    return render(request, 'edit.html', {'blog':blog})

def update(request, id):
    if request.method == 'POST':
        update_blog = BLog.objects.get(id = id)
        update_blog.title = request.POST['title']
        update_blog.author = request.POST['author']
        update_blog.body = request.POST['body']
        update_blog.save()
        return redirect('detail', update_blog.id)
    else:
        blog = BLog.objects.get(id = id)
        return render(request, 'edit.html', {'blog':blog})

def delete(request, id):
    delete_blog = BLog.objects.get(id = id)
    delete_blog.delete()
    return redirect('blog_views')

def make_post(request):
    if request.method == 'POST':
        new_blog = BLog()
        new_blog.title = request.POST['title']
        new_blog.author = request.POST['author']
        new_blog.image = request.FILES.get('image')
        new_blog.body = request.POST['body']
        new_blog.pub_date = timezone.now()
        new_blog.save()
        return redirect('blog_views')
    else:
        return render(request,'new.html')

# 이 두 함수의 차이점은 render의 경우 내가 가진 templates를 data를 넣어 보내고 싶을 때 이용하고, redirect는 내가 가진 templates뿐만 아니라 절대 url로 이동하고 싶을 때에도 이용할 수 있다는 거죠

def create_comment(request, blog_id):
    if request.method == "POST":
        comment = Comment()
        comment.blog = get_object_or_404(BLog, pk=blog_id)
        comment.author = request.POST['author']
        comment.content = request.POST['content']
        comment.create_at = timezone.datetime.now()
        comment.save()

        return redirect('detail', blog_id)

def delete_comment(request, blog_id, comment_id):
    my_comment = Comment.objects.get(pk=comment_id)
    my_comment.delete()
    return redirect('detail', blog_id)

account/templates/form_errors.html
<!-- users>form_errors.html -->

{% if form.errors %}
{% for field in form %}
{% for error in field.errors %}
<!-- 필드 오류를 출력한다. -->
<div>
  <strong>{{ field.label }}</strong>
  {{ error }}
</div>
{% endfor %}
{% endfor %}
{% for error in form.non_field_errors %}
<!-- 넌필드 오류를 출력한다. -->
<div>
  <strong>{{ error }}</strong>
</div>
{% endfor %}
{% endif %}

account/templates/login.html
{% load static %}
{% block content %}

<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Hugo 0.104.2">
  <title>Signin Template · Bootstrap v5.2</title>

  <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/sign-in/">





  <link href="{% static 'bootstrap.min.css' %}" rel="stylesheet">

  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }

    .b-example-divider {
      height: 3rem;
      background-color: rgba(0, 0, 0, .1);
      border: solid rgba(0, 0, 0, .15);
      border-width: 1px 0;
      box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
    }

    .b-example-vr {
      flex-shrink: 0;
      width: 1.5rem;
      height: 100vh;
    }

    .bi {
      vertical-align: -.125em;
      fill: currentColor;
    }

    .nav-scroller {
      position: relative;
      z-index: 2;
      height: 2.75rem;
      overflow-y: hidden;
    }

    .nav-scroller .nav {
      display: flex;
      flex-wrap: nowrap;
      padding-bottom: 1rem;
      margin-top: -1px;
      overflow-x: auto;
      text-align: center;
      white-space: nowrap;
      -webkit-overflow-scrolling: touch;
    }
  </style>


  <!-- Custom styles for this template -->
  <link href="{% static 'login.css' %}" rel="stylesheet">
</head>

<body class="text-center">

  <main class="form-signin w-100 m-auto">
      <img class="mb-4" src="{% static 'LikeLion.png' %}" alt="" width="72" height="57">
      <h1 class="h3 mb-3 fw-normal">Please sign in</h1>
      <form method="POST" action="{% url 'users:login' %}" >
        {% csrf_token %}
        <div class="form-floating">
          <input type="text" class="form-control" id="floatingInput" placeholder="Type your name" name="username">
          <label for="floatingInput">your_name</label>
        </div>
        <div class="form-floating">
          <input type="password" class="form-control" id="floatingPassword" placeholder="Password" name="password">
          <label for="floatingPassword">Password</label>
        </div>
      

      <!-- <div class="checkbox mb-3">
      <label>
        <input type="checkbox" value="remember-me"> Remember me
      </label>
    </div> -->
      <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
      
      <p class="mt-5 mb-3 text-muted">Copyright&copy; Yongjun-hong. All rights reserved </p>
    </form>
  </main>
  {% endblock %}
</body>

</html>

account/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>    
        @font-face {
        font-family: 'MapoFlowerIsland';
        src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2001@1.1/MapoFlowerIslandA.woff') format('woff');
        font-weight: normal;
        font-style: normal;
        }
        .all{
            font-family: 'MapoFlowerIsland';
            text-decoration: none;
            align-items: center;
            height: 100%;
            line-height: 100%;
            text-align: center;
            margin-top: 15%;
        }
        .loginbox, .loginbtn{
            height: 30px;
            width: 300px;
            margin: 5px;
            font-size: 17px;
            align-items: center;
        }

        .loginbtn{
            background-color:lightseagreen;
            color: white;
            border: 0;
            outline: 0;
        }

        </style>
</head>
<body>
    <div class="all">
        <form method="POST" action="{% url 'users:signup' %}">
            {% csrf_token %}
            <p>username</p>
            <input class="loginbox" type="text" name="username">
            <br>
            <p>password</p>
            <input class="loginbox" type="password" name="password">
            <br>
            <p>confirm</p>
            <input class="loginbox" type="password" name="confirm">
            <br>
            <input class="loginbtn" type="submit" value="회원가입">
        </form>        
    </div>

</body>
</html>